#!/usr/bin/env python3
"""
LLMSpaghetti First-Boot Web Wizard
Runs once on first boot on port 80.
Collects config from the user via a browser, writes all config files,
starts the main stack, then disables itself permanently.
"""

import os
import json
import subprocess
import secrets
import hashlib
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, Request, Form
from fastapi.responses import HTMLResponse, RedirectResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
import uvicorn

INSTALL_DIR = Path(os.environ.get("INSTALL_DIR", "/opt/llmspaghetti"))
STACK_DIR   = INSTALL_DIR
CONFIG_DIR  = INSTALL_DIR / "config"
LOG_DIR     = INSTALL_DIR / "logs"
DONE_FLAG   = INSTALL_DIR / ".firstboot-complete"
SELECTED_MODELS_FILE = LOG_DIR / "selected_models.json"

app = FastAPI(title="LLMSpaghetti Setup")
templates = Jinja2Templates(directory=str(Path(__file__).parent / "templates"))

# ── Helpers ──────────────────────────────────────────────────────────────────

def run(cmd, check=False):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True, check=check)


def get_gpu_info():
    gpu_file = INSTALL_DIR / "gpu-info.json"
    if gpu_file.exists():
        with open(gpu_file) as f:
            return json.load(f)
    return {"driver_stack": "unknown", "total_vram_gb": 0, "model_tier": "cpu"}


def get_ip():
    import socket
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except Exception:
        return "unknown"


def model_suggestions(tier):
    """Suggest starter models based on GPU VRAM tier."""
    suggestions = {
        "large": [
            {"id": "llama3:70b",        "name": "Llama 3 70B",         "size": "40GB", "desc": "Best quality, needs 40GB+ VRAM"},
            {"id": "mixtral:8x7b",      "name": "Mixtral 8×7B",        "size": "26GB", "desc": "Fast MoE model, great for coding"},
            {"id": "codellama:34b",     "name": "CodeLlama 34B",       "size": "19GB", "desc": "Best coding model"},
            {"id": "llama3:8b",         "name": "Llama 3 8B",          "size": "4.7GB","desc": "Fast everyday model"},
        ],
        "medium": [
            {"id": "llama3:8b",         "name": "Llama 3 8B",          "size": "4.7GB","desc": "Best all-rounder for your GPU"},
            {"id": "mistral:7b",        "name": "Mistral 7B",          "size": "4.1GB","desc": "Fast and capable"},
            {"id": "codellama:13b",     "name": "CodeLlama 13B",       "size": "7.4GB","desc": "Good coding model"},
            {"id": "deepseek-coder:6.7b","name":"DeepSeek Coder 6.7B", "size": "3.8GB","desc": "Excellent for code"},
        ],
        "small": [
            {"id": "llama3:8b",         "name": "Llama 3 8B",          "size": "4.7GB","desc": "Best you can run, may be slow"},
            {"id": "mistral:7b",        "name": "Mistral 7B",          "size": "4.1GB","desc": "Good all-rounder"},
            {"id": "phi3:mini",         "name": "Phi-3 Mini",          "size": "2.3GB","desc": "Small but smart, fits easily"},
            {"id": "deepseek-coder:6.7b","name":"DeepSeek Coder 6.7B", "size": "3.8GB","desc": "Coding focused"},
        ],
        "tiny": [
            {"id": "phi3:mini",         "name": "Phi-3 Mini",          "size": "2.3GB","desc": "Recommended for your GPU"},
            {"id": "gemma:2b",          "name": "Gemma 2B",            "size": "1.4GB","desc": "Very small and fast"},
        ],
        "cpu": [
            {"id": "qwen2:0.5b",        "name": "Qwen2 0.5B",          "size": "0.4GB","desc": "Tiny & fast — great for testing on CPU"},
            {"id": "phi3:mini",         "name": "Phi-3 Mini",          "size": "2.3GB","desc": "Best quality for CPU inference"},
            {"id": "gemma:2b",          "name": "Gemma 2B",            "size": "1.4GB","desc": "Small and fast on CPU"},
            {"id": "llama3:8b",         "name": "Llama 3 8B (slow)",   "size": "4.7GB","desc": "Will be slow on CPU"},
        ],
    }
    return suggestions.get(tier, suggestions["cpu"])


# ── Config writers ────────────────────────────────────────────────────────────

def write_litellm_config(form_data):
    """Generate litellm_config.yaml from wizard form data."""
    master_key = f"sk-spag-{secrets.token_hex(16)}"

    lines = [
        "# LiteLLM Proxy — generated by LLMSpaghetti first-boot wizard",
        "# Edit with: spag config",
        "",
        "model_list:",
        "",
        "  # Local models via Ollama",
        "  - model_name: local-default",
        "    litellm_params:",
        f"      model: ollama/{form_data.get('local_model', 'qwen2:0.5b')}",
        "      api_base: http://host.docker.internal:11434",
        "",
    ]

    if form_data.get("anthropic_key"):
        lines += [
            "  # Anthropic Claude",
            "  - model_name: claude-sonnet",
            "    litellm_params:",
            "      model: anthropic/claude-sonnet-4-6",
            '      api_key: "${ANTHROPIC_API_KEY}"',
            "",
            "  - model_name: claude-opus",
            "    litellm_params:",
            "      model: anthropic/claude-opus-4-6",
            '      api_key: "${ANTHROPIC_API_KEY}"',
            "",
        ]

    if form_data.get("openai_key"):
        lines += [
            "  # OpenAI",
            "  - model_name: gpt-4o",
            "    litellm_params:",
            "      model: openai/gpt-4o",
            '      api_key: "${OPENAI_API_KEY}"',
            "",
            "  - model_name: gpt-4o-mini",
            "    litellm_params:",
            "      model: openai/gpt-4o-mini",
            '      api_key: "${OPENAI_API_KEY}"',
            "",
        ]

    if form_data.get("groq_key"):
        lines += [
            "  # Groq (fast inference)",
            "  - model_name: groq-llama3",
            "    litellm_params:",
            "      model: groq/llama3-70b-8192",
            '      api_key: "${GROQ_API_KEY}"',
            "",
        ]

    lines += [
        "litellm_settings:",
        "  drop_params: true",
        "  request_timeout: 600",
        "  num_retries: 2",
        "",
        "general_settings:",
        "  # No master_key — LiteLLM is internal-only (Docker network).",
        "  # The router handles external authentication.",
    ]

    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    config_path = CONFIG_DIR / "litellm_config.yaml"
    config_path.write_text("\n".join(lines))

    # Save master key separately so the console can show it
    (CONFIG_DIR / "master_key").write_text(master_key)
    (CONFIG_DIR / "master_key").chmod(0o600)

    return master_key


def write_router_roles_config(form_data):
    """Write router_roles.yaml with the best available model per role."""
    has_anthropic = bool(form_data.get("anthropic_key"))
    has_openai    = bool(form_data.get("openai_key"))
    has_groq      = bool(form_data.get("groq_key"))

    roles = {
        "image":     "dall-e-3"      if has_openai   else "local-default",
        "code":      "claude-sonnet" if has_anthropic else "local-default",
        "reasoning": "claude-opus"   if has_anthropic else "local-default",
        "fast":      "groq-llama3"   if has_groq      else "local-default",
        "document":  "claude-sonnet" if has_anthropic else "local-default",
        "general":   "local-default",
        "none":      None,
    }

    lines = [
        "# LLMSpaghetti Router — Role → Model mapping",
        "# Generated by first-boot wizard. Edit with: spag config",
        "# Model names must match model_name entries in litellm_config.yaml",
        "",
        "roles:",
    ]
    for role, model in roles.items():
        if model is None:
            lines.append(f"  {role}: null")
        else:
            lines.append(f'  {role}: "{model}"')

    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    (CONFIG_DIR / "router_roles.yaml").write_text("\n".join(lines) + "\n")


def apply_system_settings(form_data):
    """Apply hostname, timezone, SSH settings."""
    hostname = form_data.get("hostname", "llmspaghetti").strip() or "llmspaghetti"
    timezone = form_data.get("timezone", "UTC").strip() or "UTC"

    run(f"hostnamectl set-hostname {hostname}")
    run(f"timedatectl set-timezone {timezone}")

    if form_data.get("ssh_key"):
        ssh_dir = Path("/home/llmspaghetti/.ssh")
        ssh_dir.mkdir(mode=0o700, exist_ok=True)
        auth_keys = ssh_dir / "authorized_keys"
        with open(auth_keys, "a") as f:
            f.write(form_data["ssh_key"].strip() + "\n")
        auth_keys.chmod(0o600)
        run("chown -R llmspaghetti:llmspaghetti /home/llmspaghetti/.ssh")


def start_stack():
    """Pull images and start the stack in the background.

    Firstboot runs on port 3001 so it stays alive (serving the done page
    with live status polling) while Docker images download. Once Open WebUI
    is healthy on port 3000, we switch the Caddyfile and stop firstboot.
    """
    compose = f"docker compose -f {INSTALL_DIR}/docker-compose.yml"
    log = open(INSTALL_DIR / "logs" / "stack-startup.log", "w")
    switch_caddyfile = (
        "printf ':80 {\\n"
        "    handle /api/* { uri strip_prefix /api; reverse_proxy localhost:4000 }\\n"
        "    handle { reverse_proxy localhost:3000 }\\n"
        "    encode gzip\\n"
        "}\\n' > /etc/caddy/Caddyfile"
        " && systemctl reload caddy"
        " && systemctl stop llmspaghetti-firstboot.service"
    )
    subprocess.Popen(
        f"{compose} pull"
        f" && {compose} up -d"
        f" && systemctl enable llmspaghetti"
        f" && until curl -sf http://localhost:3000 > /dev/null 2>&1; do sleep 5; done"
        f" && {switch_caddyfile}",
        shell=True, stdout=log, stderr=log,
    )


def pull_models_background(model_ids):
    """Kick off model pulls in background processes."""
    for model_id in model_ids:
        subprocess.Popen(
            ["ollama", "pull", model_id],
            stdout=open(INSTALL_DIR / "logs" / f"pull-{model_id.replace(':', '-')}.log", "w"),
            stderr=subprocess.STDOUT,
        )


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/", response_class=HTMLResponse)
async def wizard_welcome(request: Request):
    if DONE_FLAG.exists():
        return RedirectResponse("/done")
    gpu = get_gpu_info()
    return templates.TemplateResponse(request, "welcome.html", {
        "gpu": gpu,
        "ip": get_ip(),
    })


@app.get("/step/system", response_class=HTMLResponse)
async def wizard_system(request: Request):
    hostname = run("hostname").stdout.strip() or "llmspaghetti"
    timezone = run("timedatectl show -p Timezone --value").stdout.strip() or "UTC"
    return templates.TemplateResponse(request, "step_system.html", {
        "hostname": hostname,
        "timezone": timezone,
    })


@app.get("/step/models", response_class=HTMLResponse)
async def wizard_models(request: Request):
    gpu = get_gpu_info()
    tier = gpu.get("model_tier", "cpu")
    suggestions = model_suggestions(tier)
    return templates.TemplateResponse(request, "step_models.html", {
        "gpu": gpu,
        "suggestions": suggestions,
    })


@app.get("/step/apikeys", response_class=HTMLResponse)
async def wizard_apikeys(request: Request):
    return templates.TemplateResponse(request, "step_apikeys.html")


@app.get("/step/confirm", response_class=HTMLResponse)
async def wizard_confirm(request: Request):
    gpu = get_gpu_info()
    return templates.TemplateResponse(request, "step_confirm.html", {
        "gpu": gpu,
        "ip": get_ip(),
    })


@app.post("/setup/apply")
async def apply_setup(
    request: Request,
    hostname:      str = Form("llmspaghetti"),
    timezone:      str = Form("UTC"),
    ssh_key:       str = Form(""),
    anthropic_key: str = Form(""),
    openai_key:    str = Form(""),
    groq_key:      str = Form(""),
    models:        str = Form(""),   # comma-separated model IDs
):
    if DONE_FLAG.exists():
        return JSONResponse({"status": "already_done"})

    model_list = [m.strip() for m in models.split(",") if m.strip()]

    form_data = {
        "hostname":      hostname,
        "timezone":      timezone,
        "ssh_key":       ssh_key,
        "anthropic_key": anthropic_key,
        "openai_key":    openai_key,
        "groq_key":      groq_key,
        # The first model the user picked becomes the local-default.
        # Falls back to a tiny CPU-friendly model if none selected.
        "local_model":   model_list[0] if model_list else "qwen2:0.5b",
    }

    # Apply settings
    apply_system_settings(form_data)
    master_key = write_litellm_config(form_data)
    write_router_roles_config(form_data)

    # Pull models BEFORE starting the stack so local-default exists when
    # LiteLLM first tries to reach it. Record the selection so /api/status can
    # report per-model download progress on the done page.
    if model_list:
        try:
            LOG_DIR.mkdir(parents=True, exist_ok=True)
            SELECTED_MODELS_FILE.write_text(json.dumps(model_list))
        except Exception:
            pass
        pull_models_background(model_list)
    start_stack()

    # Mark first boot complete — wizard won't run again
    DONE_FLAG.touch()

    # Disable this service (self-destruct)
    run("systemctl disable llmspaghetti-firstboot.service")

    return JSONResponse({
        "status":     "ok",
        "master_key": master_key,
        "ip":         get_ip(),
        "models":     model_list,
    })


@app.get("/done", response_class=HTMLResponse)
async def wizard_done(request: Request):
    master_key_file = CONFIG_DIR / "master_key"
    master_key = master_key_file.read_text() if master_key_file.exists() else "see /opt/llmspaghetti/config/litellm_config.yaml"
    return templates.TemplateResponse(request, "done.html", {
        "ip":         get_ip(),
        "master_key": master_key,
    })


def _download_status():
    """Per-model download progress, read from the ollama pull logs.

    Shows the actual last status line from each pull (e.g. 'pulling <hash>: 45%'
    or 'verifying sha256 digest') so the user sees exactly what's happening —
    nothing hidden. A model is 'done' once it appears in `ollama list`.
    """
    try:
        selected = json.loads(SELECTED_MODELS_FILE.read_text())
    except Exception:
        return []
    have = set(run("ollama list 2>/dev/null | tail -n +2 | awk '{print $1}'").stdout.split())
    out = []
    for m in selected:
        done = m in have
        status = "downloaded" if done else "starting…"
        if not done:
            logf = LOG_DIR / f"pull-{m.replace(':', '-')}.log"
            if logf.exists():
                try:
                    # ollama uses \r to redraw progress — treat CRs as newlines
                    raw   = logf.read_text(errors="ignore").replace("\r", "\n")
                    lines = [l.strip() for l in raw.splitlines() if l.strip()]
                    if lines:
                        status = lines[-1]
                except Exception:
                    pass
        out.append({"model": m, "done": done, "status": status})
    return out


@app.get("/api/status")
async def api_status():
    """Live status endpoint polled by the browser during setup."""
    from datetime import datetime

    def svc(name):
        return run(f"systemctl is-active {name} 2>/dev/null").stdout.strip()

    def container(name):
        return run(f"docker inspect -f '{{{{.State.Status}}}}' {name} 2>/dev/null").stdout.strip() or "absent"

    webui   = container("llmspaghetti-webui")
    litellm = container("llmspaghetti-litellm")
    # Is Open WebUI actually serving yet? (container "running" != HTTP ready)
    http = run("curl -sf -o /dev/null -w '%{http_code}' --max-time 3 http://localhost:3000").stdout.strip()
    webui_ready = http == "200"

    if webui_ready:
        stage, stage_msg = "ready", "Open WebUI is up — you can start chatting."
    elif webui == "running":
        stage, stage_msg = "starting", "Services started — waiting for Open WebUI to finish booting…"
    elif webui in ("created", "restarting"):
        stage, stage_msg = "starting", "Starting containers…"
    else:
        stage, stage_msg = "preparing", "Downloading container images (~2 GB, one-time)…"

    return JSONResponse({
        "timestamp": datetime.utcnow().isoformat(),
        "stage": stage,
        "stage_msg": stage_msg,
        "webui_ready": webui_ready,
        "services": {
            "ollama":   svc("ollama"),
            "webui":    webui,
            "litellm":  litellm,
            "cockpit":  svc("cockpit.socket"),   # socket-activated; .service is idle until connect
        },
        "downloads": _download_status(),
        "models": run("ollama list 2>/dev/null | tail -n +2 | awk '{print $1}'").stdout.splitlines(),
    })


if __name__ == "__main__":
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=int(os.environ.get("PORT", 3001)),
        log_level="warning",
        access_log=False,
    )
